#!/usr/bin/env python3
"""
Repair a conda-based virtualenv on Windows, once, so everything in it works.

    python robotic_testing/setup_windows_env.py           fix the active environment
    python robotic_testing/setup_windows_env.py --check   report, change nothing

Run it with the environment you actually use already activated -- it fixes the
interpreter that runs it, and nothing else.

WHY THIS EXISTS

A venv built from a conda interpreter cannot import parts of its own standard
library. `robotic_testing/common/windows_dlls.py` explains the mechanism in
full; the short version is that conda keeps the DLLs its stdlib C extensions
need in `Library\\bin`, a venv does not inherit that directory, and Python 3.8+
will not find DLLs through PATH. The symptoms:

    ImportError: DLL load failed while importing _ssl      -- no https, so no pip,
                                                              and no google-genai
    ImportError: DLL load failed while importing _sqlite3   -- the Jupyter server
                                                              exits with code 1

Repo code fixes itself by importing windows_dlls. The Jupyter server cannot: it
dies inside `import notebook`, long before any repo module is reached. So the
same fix has to live where Python will run it during interpreter startup, and
that place is a `sitecustomize.py` on sys.path -- imported by `site` at the end
of initialization, before __main__, before any third-party package.

That file is what this script installs. It is written to compute its directories
from sys.base_prefix at run time, so it hardcodes no paths and stays correct if
the environment is rebuilt or conda is installed somewhere else.

WHAT IT TOUCHES

One file, inside the environment:  <env>\\Lib\\site-packages\\sitecustomize.py

Nothing in the repository, nothing global, nothing outside the active
environment. A `sitecustomize.py` that this script did not write is never
overwritten -- it is backed up first and the path is printed.
"""
import argparse
import os
import subprocess
import sys
import sysconfig

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if REPO_ROOT not in sys.path:
    sys.path.insert(0, REPO_ROOT)

from robotic_testing.common import windows_dlls  # noqa: E402

# How we recognise our own handiwork, so a re-run replaces it instead of
# refusing, and a file somebody else wrote is never clobbered.
MARKER = '# generated by robotic_testing/setup_windows_env.py'

SITECUSTOMIZE = '''\
{marker}
"""
Let this environment import its own standard library.

This venv's base interpreter keeps the DLLs its stdlib C extensions need (_ssl,
_sqlite3, _hashlib, _lzma, _bz2, _ctypes) in directories a venv does not
inherit, and since Python 3.8 DLL resolution for extension modules ignores PATH.
Without this file those imports fail with "DLL load failed", which takes out
https (pip, google-genai) and the Jupyter server's session store.

`site` imports this module during interpreter startup, before __main__ and
before any third-party package, which is the only point early enough to help a
process like the Jupyter server that fails inside its own imports.

Regenerate with:  python robotic_testing/setup_windows_env.py
Explanation in:   robotic_testing/common/windows_dlls.py
"""
import os
import sys


def _add_base_dll_directories():
    if os.name != 'nt' or not hasattr(os, 'add_dll_directory'):
        return
    root = getattr(sys, 'base_prefix', sys.prefix)
    for parts in {subdirs!r}:
        path = os.path.join(root, *parts)
        if os.path.isdir(path):
            try:
                os.add_dll_directory(path)
            except OSError:
                pass


# Anything raised here would break every interpreter start in this environment,
# including the one needed to undo it, so nothing is allowed to escape.
try:
    _add_base_dll_directories()
except Exception:
    pass
'''

PROBE = ('import ssl, sqlite3, hashlib, lzma, bz2, ctypes; '
         'print(ssl.OPENSSL_VERSION); print(sqlite3.sqlite_version)')

MODULES = ('ssl', 'sqlite3', 'hashlib', 'lzma', 'bz2', 'ctypes')


def site_packages():
    """The active environment's site-packages, where sitecustomize.py belongs."""
    path = sysconfig.get_paths().get('purelib')
    if not path:
        raise SystemExit('Cannot locate site-packages for {}'.format(sys.executable))
    return path


def probe(module):
    """
    Import `module` in a fresh interpreter and report the failure, if any.

    A subprocess rather than a plain import, because that is the thing we
    actually care about: whether a *newly started* process in this environment
    can import it. This process may already have had the fix applied in memory.
    """
    result = subprocess.run(
        [sys.executable, '-c', 'import ' + module],
        stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    if result.returncode == 0:
        return None
    lines = [line for line in result.stderr.decode('utf-8', 'replace').splitlines() if line.strip()]
    return lines[-1] if lines else 'exited {}'.format(result.returncode)


def report():
    """Print what a fresh interpreter in this environment can and cannot import."""
    print('Environment')
    print('  python        {}'.format(sys.executable))
    print('  version       {}'.format(sys.version.split()[0]))
    print('  base prefix   {}'.format(windows_dlls.base_prefix()))
    if sys.prefix == windows_dlls.base_prefix():
        print('                (not a venv)')
    print('  {}'.format(windows_dlls.describe().replace('\n', '\n  ')))

    target = os.path.join(site_packages(), 'sitecustomize.py')
    if os.path.exists(target):
        with open(target, 'r', encoding='utf-8', errors='replace') as handle:
            mine = MARKER in handle.read()
        print('  sitecustomize {}  ({})'.format(target, 'ours' if mine else 'not ours'))
    else:
        print('  sitecustomize not installed')

    print('\nImports, in a fresh interpreter')
    broken = []
    for module in MODULES:
        failure = probe(module)
        if failure:
            broken.append(module)
            print('  {:<9} FAILED  {}'.format(module, failure))
        else:
            print('  {:<9} ok'.format(module))
    return broken


def install():
    """Write sitecustomize.py into the active environment. Returns its path."""
    target = os.path.join(site_packages(), 'sitecustomize.py')

    if os.path.exists(target):
        with open(target, 'r', encoding='utf-8', errors='replace') as handle:
            existing = handle.read()
        if MARKER not in existing:
            # Somebody else's file. Keep it: it may be doing something this script
            # knows nothing about, and silently replacing it would be a bad trade.
            backup = target + '.bak'
            suffix = 0
            while os.path.exists(backup):
                suffix += 1
                backup = '{}.bak{}'.format(target, suffix)
            os.rename(target, backup)
            print('Moved an existing sitecustomize.py aside:')
            print('  {}'.format(backup))
            print('  If it mattered, merge it into the new one by hand.')

    with open(target, 'w', encoding='utf-8') as handle:
        handle.write(SITECUSTOMIZE.format(
            marker=MARKER, subdirs=windows_dlls._CONDA_DLL_SUBDIRS))
    return target


def main(argv=None):
    parser = argparse.ArgumentParser(
        description='Repair a conda-based virtualenv on Windows so it can import '
                    'ssl, sqlite3 and the rest of its own standard library.')
    parser.add_argument('--check', action='store_true',
                        help='report what works and what does not, and change nothing')
    args = parser.parse_args(argv)

    if os.name != 'nt':
        print('Not Windows -- nothing to fix. ({})'.format(sys.platform))
        print('This script exists for venvs built from a conda interpreter on Windows;')
        print('every other platform finds its stdlib DLLs without help.')
        return 0

    broken = report()

    if args.check:
        print()
        print('Nothing changed (--check).')
        if broken:
            print('Fix it with:  python robotic_testing/setup_windows_env.py')
        return 1 if broken else 0

    if not broken:
        print('\nNothing to fix: this environment already imports everything it needs.')
        return 0

    print()
    target = install()
    print('Installed:\n  {}'.format(target))

    print('\nImports, in a fresh interpreter, after the fix')
    still_broken = []
    for module in MODULES:
        failure = probe(module)
        if failure:
            still_broken.append(module)
            print('  {:<9} FAILED  {}'.format(module, failure))
        else:
            print('  {:<9} ok'.format(module))

    if still_broken:
        print('\nStill broken: {}'.format(', '.join(still_broken)))
        print('The DLLs those modules need are not under {}.'.format(
            windows_dlls.base_prefix()))
        print('Rebuilding the venv on a python.org interpreter avoids this entirely:')
        print('    py -3.11 -m venv .venv')
        print('    .\\.venv\\Scripts\\Activate.ps1')
        print('    python -m pip install -r robotic_testing\\requirements-vla.txt')
        print('    python -m pip install jupyter ipykernel')
        return 1

    print('\nDone. This environment is fixed for good -- no need to run this again.')
    print('Restart anything already running in it (the PyCharm Jupyter server in')
    print('particular: stop it with the square button, then re-run a cell).')
    return 0


if __name__ == '__main__':
    sys.exit(main())
