#!/usr/bin/env python3
"""
Repair a conda-based virtualenv on Windows, once, so everything in it works.

    python robotic_testing/setup_windows_env.py             fix this repo's .venv
    python robotic_testing/setup_windows_env.py --check     report, change nothing
    python robotic_testing/setup_windows_env.py --env PATH  fix some other environment
    python robotic_testing/setup_windows_env.py --here      fix the interpreter running this

WHY THIS EXISTS

A venv built from a conda interpreter cannot import parts of its own standard
library. `robotic_testing/common/windows_dlls.py` explains the mechanism in
full; the short version is that conda keeps the DLLs its stdlib C extensions
need in `Library\\bin`, a venv does not inherit that directory, and Python 3.8+
will not find DLLs through PATH. The symptoms:

    ImportError: DLL load failed while importing _ssl      -- no https, so no pip,
                                                              and no google-genai
    ImportError: DLL load failed while importing _sqlite3   -- the Jupyter server
                                                              exits with code 1

vla.py and listen.py import windows_dlls themselves, so they fix their own
process and work with no setup at all. The Jupyter server cannot do that: it
dies inside `import notebook`, long before any repo module is reached. Which is
exactly the maddening case where the scripts run and the notebook does not.

So the same fix has to live where Python runs it during interpreter startup,
and that place is a `sitecustomize.py` on sys.path -- imported by `site` at the
end of initialization, before __main__, before any third-party package.

WHICH ENVIRONMENT IT FIXES

This is the part that bites. `sitecustomize.py` belongs to one environment, and
the broken one is not necessarily the one running this script: on the lab
machine a bare `python` resolves to miniconda even with .venv activated, and
miniconda's own interpreter is fine. Pointed at that, an earlier version of
this script truthfully reported "nothing to fix" and left .venv broken.

So the target is this repo's .venv by default, not whatever is running. --env
names another one; --here means the running interpreter on purpose. Everything
below -- the probes, site-packages, the DLL directories -- is asked of the
*target* interpreter in a subprocess, never inferred from this one.

WHAT IT TOUCHES

One file, inside the target environment:

    <env>\\Lib\\site-packages\\sitecustomize.py

Nothing in the repository, nothing global, nothing outside that environment. A
`sitecustomize.py` this script did not write is never overwritten -- it is
backed up first and the path is printed.
"""
import argparse
import os
import subprocess
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if REPO_ROOT not in sys.path:
    sys.path.insert(0, REPO_ROOT)

from robotic_testing.common import windows_dlls  # noqa: E402

MARKER = '# generated by robotic_testing/setup_windows_env.py'

SITECUSTOMIZE = '''\
{marker}
"""
Let this environment import its own standard library.

This venv's base interpreter keeps the DLLs its stdlib C extensions need (_ssl,
_sqlite3, _hashlib, _lzma, _bz2, _ctypes) in directories a venv does not
inherit, and since Python 3.8 DLL resolution for extension modules ignores PATH.
Without this file those imports fail with "DLL load failed", which takes out
https (pip, google-genai) and the Jupyter server's session store.

`site` imports this module during interpreter startup, before __main__ and
before any third-party package, which is the only point early enough to help a
process like the Jupyter server that fails inside its own imports.

Regenerate with:  python robotic_testing/setup_windows_env.py
Explanation in:   robotic_testing/common/windows_dlls.py
"""
import os
import sys


def _add_base_dll_directories():
    if os.name != 'nt' or not hasattr(os, 'add_dll_directory'):
        return
    root = getattr(sys, 'base_prefix', sys.prefix)
    directories = [os.path.join(root, *parts) for parts in {subdirs!r}]
    # Found by searching the base prefix, because a DLL was not in any of the
    # conventional places above. Absolute, so they do not move with sys.base_prefix;
    # re-run the setup script if this environment is rebuilt elsewhere.
    directories += {extra!r}
    for path in directories:
        if os.path.isdir(path):
            try:
                os.add_dll_directory(path)
            except OSError:
                pass


def _preload(patterns):
    """
    Load these DLLs by absolute path, before anything imports the module needing them.

    add_dll_directory is not always enough. It covers the *direct* dependencies of an
    extension module, but a dependency of a dependency can still come up missing --
    which is how _sqlite3 fails with "DLL load failed" while sqlite3.dll sits in a
    directory that was added, and while _ssl loads from that same directory.

    Loading by full path sidesteps the search entirely: once a DLL is in the process,
    the loader satisfies later references to it by name without touching the
    filesystem. So this pins them first and the search never has to succeed.
    """
    import ctypes
    import glob

    root = getattr(sys, 'base_prefix', sys.prefix)
    for parts in {subdirs!r}:
        directory = os.path.join(root, *parts)
        if not os.path.isdir(directory):
            continue
        for pattern in patterns:
            for path in sorted(glob.glob(os.path.join(directory, pattern))):
                try:
                    ctypes.WinDLL(path)
                except OSError:
                    pass        # a wrong-architecture or already-loaded copy; move on


# Anything raised here would break every interpreter start in this environment,
# including the one needed to undo it, so nothing is allowed to escape.
try:
    _add_base_dll_directories()
    _preload({preload!r})
except Exception:
    pass
'''

# The stdlib extensions that conda keeps DLLs for. _sqlite3 is the one that stops
# Jupyter; _ssl is the one that stops pip and the planner.
STDLIB_PROBES = ('ssl', 'sqlite3', 'hashlib', 'lzma', 'bz2', 'ctypes')

# Pinned into the process at startup, in this order. The stdlib's own dependencies
# first, then the runtime libraries those are themselves built against -- which are
# the transitive ones that go missing and cannot be named from the failure message.
PRELOAD = (
    'zlib.dll', 'zlib1.dll', 'libz*.dll',
    'vcruntime140*.dll', 'msvcp140*.dll', 'concrt140*.dll',
    'libcrypto*.dll', 'libssl*.dll',
    'sqlite3.dll',
    'liblzma*.dll', 'libbz2*.dll', 'bzip2*.dll', 'libffi*.dll',
)

# The notebook server's own import chain, which is what actually fails in PyCharm.
# Reported only when the package is installed at all: not every environment has
# Jupyter, and a missing notebook is not a DLL problem.
JUPYTER_PROBES = (
    ('notebook.services.sessions.sessionmanager', 'the notebook session store (sqlite3)'),
    ('notebook.notebookapp', 'the notebook server entry point'),
    ('ipykernel', 'the kernel PyCharm starts'),
    ('zmq', 'kernel messaging'),
)


class Failure(Exception):
    """Something the operator needs to fix, reported without a traceback."""


class Environment:
    """One Python environment, asked about itself in a subprocess."""

    def __init__(self, python):
        self.python = os.path.abspath(python)
        if not os.path.isfile(self.python):
            raise Failure('No interpreter at {}'.format(self.python))

    # --- asking the target, never guessing from this process ---------------

    def query(self, expression):
        """Evaluate `expression` in the target and return its printed value."""
        result = subprocess.run(
            [self.python, '-c', 'print({})'.format(expression)],
            stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        if result.returncode != 0:
            raise Failure('{} could not answer `{}`:\n{}'.format(
                self.python, expression,
                result.stderr.decode('utf-8', 'replace').strip()))
        return result.stdout.decode('utf-8', 'replace').strip()

    def probe(self, module):
        """Import `module` in a fresh target interpreter; return the error or None."""
        result = subprocess.run(
            [self.python, '-c', 'import ' + module],
            stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        if result.returncode == 0:
            return None
        lines = [line for line in result.stderr.decode('utf-8', 'replace').splitlines()
                 if line.strip()]
        return lines[-1] if lines else 'exited {}'.format(result.returncode)

    def presence(self, module):
        """
        'present', 'absent', or 'unknown' -- is this module here, without importing it?

        Asked separately from importing, because the two are different questions and the
        error text cannot be trusted to tell them apart. When _sqlite3 fails to load,
        `notebook` falls back to pysqlite2 and dies with "No module named 'pysqlite2'",
        which reads exactly like notebook itself being absent and is not.

        find_spec on the *full* dotted name, not the top-level package, because
        `notebook.notebookapp` genuinely does not exist in notebook 7 while `notebook`
        does -- and that is an absence, not a breakage. find_spec imports the parent
        package to look inside it, so when the parent is the broken thing the lookup
        raises; that is 'unknown', and the import error is the better answer anyway.
        """
        result = subprocess.run(
            [self.python, '-c',
             'import importlib.util, sys\n'
             'try:\n'
             '    spec = importlib.util.find_spec({!r})\n'
             'except BaseException:\n'
             '    sys.exit(2)\n'
             'sys.exit(0 if spec is not None else 1)\n'.format(module)],
            stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        state = {0: 'present', 1: 'absent'}.get(result.returncode, 'unknown')
        # The lookup raised. If the parent package is not there either, the whole name
        # is simply absent; if it is there, the parent is the broken thing.
        if state == 'unknown' and '.' in module:
            if self.presence(module.split('.')[0]) == 'absent':
                return 'absent'
        return state

    def verdict(self, module):
        """('ok'|'absent'|'broken', detail) for one module."""
        failure = self.probe(module)
        if failure is None:
            return 'ok', ''
        if self.presence(module) == 'absent':
            return 'absent', ''
        return 'broken', failure

    @property
    def version(self):
        return self.query('__import__("sys").version.split()[0]')

    @property
    def base_prefix(self):
        return self.query('getattr(__import__("sys"), "base_prefix", '
                          '__import__("sys").prefix)')

    @property
    def prefix(self):
        return self.query('__import__("sys").prefix')

    @property
    def purelib(self):
        return self.query('__import__("sysconfig").get_paths()["purelib"]')

    @property
    def is_windows(self):
        return self.query('__import__("os").name') == 'nt'

    def dll_directories(self):
        """The DLL directories that exist under the target's base prefix."""
        return windows_dlls.candidate_directories(self.base_prefix)

    @property
    def sitecustomize(self):
        return os.path.join(self.purelib, 'sitecustomize.py')

    def sitecustomize_state(self):
        """'ours', 'foreign', or 'absent'."""
        path = self.sitecustomize
        if not os.path.exists(path):
            return 'absent'
        with open(path, 'r', encoding='utf-8', errors='replace') as handle:
            return 'ours' if MARKER in handle.read() else 'foreign'


# ----------------------------------------------------------------------
# finding the environment to fix
# ----------------------------------------------------------------------

def interpreter_in(root):
    """The interpreter inside an environment directory, Windows or posix layout."""
    for parts in (('Scripts', 'python.exe'), ('bin', 'python'), ('bin', 'python3')):
        candidate = os.path.join(root, *parts)
        if os.path.isfile(candidate):
            return candidate
    return None


def repo_venv():
    """This repo's own .venv interpreter, or None."""
    for name in ('.venv', 'venv'):
        found = interpreter_in(os.path.join(REPO_ROOT, name))
        if found:
            return found
    return None


def resolve_target(env, here):
    """Decide which interpreter to work on, and say why."""
    if env and here:
        raise Failure('--env and --here ask for different environments; pick one.')

    if here:
        return Environment(sys.executable), 'the interpreter running this script (--here)'

    if env:
        # Accept either the interpreter itself or the environment directory.
        if os.path.isdir(env):
            found = interpreter_in(env)
            if not found:
                raise Failure(
                    'No interpreter under {}.\n'
                    'Expected {}\\Scripts\\python.exe (Windows) or {}/bin/python.'
                    .format(env, env.rstrip('\\/'), env.rstrip('\\/')))
            return Environment(found), 'the environment named by --env'
        return Environment(env), 'the interpreter named by --env'

    found = repo_venv()
    if found:
        return Environment(found), "this repo's .venv"

    raise Failure(
        'This repo has no .venv, so there is no default environment to fix.\n'
        'Name one:\n'
        '    python robotic_testing/setup_windows_env.py --env C:\\path\\to\\.venv\n'
        'Or fix the interpreter running this script:\n'
        '    python robotic_testing/setup_windows_env.py --here')


# ----------------------------------------------------------------------

def is_dll_failure(detail):
    """Is this failure about finding a DLL, which is the only thing here can fix?"""
    text = (detail or '').lower()
    return 'dll load failed' in text or 'specified module could not be found' in text


def report_pip_check(target):
    """Let pip say whether the installed packages agree with each other."""
    result = subprocess.run(
        [target.python, '-m', 'pip', 'check'],
        stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    text = result.stdout.decode('utf-8', 'replace').strip()
    if result.returncode == 0:
        # pip only knows about declared requirements. An old notebook against a newer
        # traitlets satisfies every pin and still cannot start, so silence here is not
        # evidence of a healthy stack and saying "no broken requirements" would read
        # as one.
        return
    print('\n  pip check says:')
    for line in text.splitlines()[:12]:
        print('    {}'.format(line))


def report(target, why):
    """Print what a fresh interpreter in the target environment can and cannot do."""
    print('Target environment -- {}'.format(why))
    print('  python        {}'.format(target.python))
    print('  version       {}'.format(target.version))
    print('  prefix        {}'.format(target.prefix))
    base = target.base_prefix
    print('  base prefix   {}'.format(base))
    if base == target.prefix:
        print('                (not a venv; its stdlib is its own)')

    if target.python != os.path.abspath(sys.executable):
        # Worth saying plainly: this difference is the whole reason the flag exists.
        print('  note          this is NOT the interpreter running this script')
        print('                ({})'.format(sys.executable))

    directories = target.dll_directories()
    if directories:
        print('  DLL dirs      {}'.format('\n                '.join(directories)))
    else:
        print('  DLL dirs      none under the base prefix (self-contained interpreter)')

    state = {'ours': 'installed by this script',
             'foreign': 'present, written by something else',
             'absent': 'not installed'}[target.sitecustomize_state()]
    print('  sitecustomize {}'.format(state))
    print('                {}'.format(target.sitecustomize))

    print('\nStandard library, in a fresh interpreter')
    broken = {}
    for module in STDLIB_PROBES:
        state, detail = target.verdict(module)
        if state == 'broken':
            broken[module] = detail
            print('  {:<9} FAILED  {}'.format(module, detail))
        else:
            print('  {:<9} {}'.format(module, state))

    # The notebook chain is reported separately because a missing Jupyter is a
    # different problem from a broken one, and only the second is ours to fix.
    print('\nThe Jupyter import chain, which is what PyCharm runs')
    any_jupyter = False
    for module, description in JUPYTER_PROBES:
        state, detail = target.verdict(module)
        if state == 'ok':
            any_jupyter = True
            print('  ok      {}  -- {}'.format(module, description))
        elif state == 'absent':
            print('  absent  {}  -- {} (not installed here)'.format(module, description))
        else:
            any_jupyter = True
            broken[module] = detail
            print('  FAILED  {}  -- {}'.format(module, description))
            print('          {}'.format(detail))
    if not any_jupyter:
        print('\n  Nothing of Jupyter is installed in this environment, so the notebook')
        print('  cannot run here regardless of DLLs:')
        print('    "{}" -m pip install jupyter ipykernel'.format(target.python))

    others = {module: detail for module, detail in broken.items() if not is_dll_failure(detail)}
    if others:
        # Worth separating loudly. Everything else this script does is about where DLLs
        # live, and none of it will help a package that is missing or a version pair
        # that does not agree.
        print('\nNot a DLL problem -- these are packages disagreeing with each other:')
        for module, detail in others.items():
            print('  {}'.format(module))
            print('    {}'.format(detail))
        print('\n  A missing jupyter_server, or a traitlets too new for an old notebook,')
        print('  both show up here. Installing a consistent Jupyter stack fixes both:')
        print('    "{}" -m pip install -U notebook jupyter_server'.format(target.python))
        report_pip_check(target)

    return broken


def discover(target, modules):
    """
    Search the target's base prefix for the DLLs `modules` need.

    Returns (directories, unfound). A module in `unfound` has no such DLL anywhere
    under the base prefix, which is a different problem: the file is missing, not
    misplaced, and no search path can conjure it.
    """
    base = target.base_prefix
    directories, unfound = [], []
    for module in modules:
        if module not in windows_dlls.MODULE_DLLS:
            continue        # not a stdlib extension we know the dependencies of
        found = windows_dlls.find_dll_directories(module, base)
        if not found:
            unfound.append(module)
            continue
        for directory in found:
            if directory not in directories:
                directories.append(directory)
    return directories, unfound


def copy_beside_interpreter(target, modules):
    """
    Copy the DLLs `modules` need into the directory holding the target's python.exe.

    The last resort, and the one thing that cannot fail to be searched: Windows always
    looks in the directory of the running executable, for an extension module's
    dependencies and for *their* dependencies too. add_dll_directory does not reach
    that far, which is the gap this closes.

    Copies rather than links, because a venv is disposable and a stale copy here is
    harmless -- and because it is trivially undone by deleting the files listed.

    :return: list of (source, destination) pairs actually copied
    """
    import glob
    import shutil

    beside = os.path.dirname(target.python)
    base = target.base_prefix
    patterns = []
    for module in modules:
        patterns += list(windows_dlls.MODULE_DLLS.get(module, ()))
    patterns += list(PRELOAD)      # the transitive runtime libraries too

    copied = []
    for parts in windows_dlls._CONDA_DLL_SUBDIRS:
        directory = os.path.join(base, *parts)
        if not os.path.isdir(directory):
            continue
        for pattern in patterns:
            for source in sorted(glob.glob(os.path.join(directory, pattern))):
                destination = os.path.join(beside, os.path.basename(source))
                if os.path.exists(destination):
                    continue        # already there; never overwrite the venv's own
                try:
                    shutil.copy2(source, destination)
                except OSError:
                    continue
                copied.append((source, destination))
    return copied


def diagnose_dlls(target, modules):
    """
    Ask the target which of these DLLs can actually be loaded, and why not.

    Run when a module is still failing after everything else: "DLL load failed" never
    names the file that is missing, but loading each candidate by hand does.
    """
    patterns = []
    for module in modules:
        patterns += list(windows_dlls.MODULE_DLLS.get(module, ()))
    patterns += list(PRELOAD)

    script = (
        'import ctypes, glob, os, sys\n'
        'root = getattr(sys, "base_prefix", sys.prefix)\n'
        'seen = set()\n'
        'for parts in %r:\n'
        '    d = os.path.join(root, *parts)\n'
        '    if not os.path.isdir(d):\n'
        '        continue\n'
        '    for pattern in %r:\n'
        '        for path in sorted(glob.glob(os.path.join(d, pattern))):\n'
        '            name = os.path.basename(path).lower()\n'
        '            if name in seen:\n'
        '                continue\n'
        '            seen.add(name)\n'
        '            try:\n'
        '                ctypes.WinDLL(path)\n'
        '            except OSError as error:\n'
        '                print("  CANNOT LOAD  %%s\\n               %%s" %% (path, error))\n'
        'if not seen:\n'
        '    print("  no candidate DLLs found at all")\n'
        % (windows_dlls._CONDA_DLL_SUBDIRS, tuple(patterns))
    )
    result = subprocess.run([target.python, '-c', script],
                            stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    return (result.stdout.decode('utf-8', 'replace').strip() or
            '  every candidate DLL loaded on its own')


def install(target, extra=()):
    """Write sitecustomize.py into the target environment. Returns its path."""
    path = target.sitecustomize

    if target.sitecustomize_state() == 'foreign':
        # Somebody else's file. Keep it: it may be doing something this script
        # knows nothing about, and silently replacing it would be a bad trade.
        backup = path + '.bak'
        suffix = 0
        while os.path.exists(backup):
            suffix += 1
            backup = '{}.bak{}'.format(path, suffix)
        os.rename(path, backup)
        print('Moved an existing sitecustomize.py aside:')
        print('  {}'.format(backup))
        print('  If it mattered, merge it into the new one by hand.')

    with open(path, 'w', encoding='utf-8') as handle:
        handle.write(SITECUSTOMIZE.format(
            marker=MARKER, subdirs=windows_dlls._CONDA_DLL_SUBDIRS,
            extra=list(extra), preload=PRELOAD))
    return path


def main(argv=None):
    parser = argparse.ArgumentParser(
        description='Repair a conda-based virtualenv on Windows so it -- and the Jupyter '
                    'server inside it -- can import ssl, sqlite3 and the rest of its own '
                    'standard library.',
        epilog='With no options it fixes this repository\'s .venv, which is the one '
               'PyCharm runs notebooks in. That is deliberately not "whichever '
               'interpreter runs this script": a bare `python` often resolves '
               'elsewhere.')
    parser.add_argument('--check', action='store_true',
                        help='report what works and what does not, and change nothing')
    parser.add_argument('--env', metavar='PATH',
                        help='the environment to fix: a directory, or a python executable')
    parser.add_argument('--here', action='store_true',
                        help='fix the interpreter running this script, whatever it is')
    args = parser.parse_args(argv)

    target, why = resolve_target(args.env, args.here)

    if not target.is_windows:
        print('{} is not on Windows, so there is nothing to fix.'.format(target.python))
        print('This script exists for venvs built from a conda interpreter on Windows;')
        print('every other platform finds its stdlib DLLs without help.')
        return 0

    broken = report(target, why)
    dll_broken = [module for module, detail in broken.items() if is_dll_failure(detail)]
    package_broken = [module for module in broken if module not in dll_broken]

    if args.check:
        print()
        if dll_broken:
            print('DLLs broken: {}'.format(', '.join(dll_broken)))
            print('Fix it with:  python robotic_testing/setup_windows_env.py')
        if package_broken:
            print('Packages broken: {} -- see the pip command above; this script'
                  .format(', '.join(package_broken)))
            print('does not install packages.')
        if not broken:
            print('Nothing to fix.')
        return 1 if broken else 0

    if not dll_broken:
        if package_broken:
            print('\nNo DLL problem left -- the remaining failures are the package')
            print('problems above, which pip fixes, not this script.')
            return 1
        print('\nNothing to fix: this environment already imports everything it needs.')
        print('If PyCharm still fails, it is running a different interpreter than this')
        print('one. Check it with a notebook cell:')
        print('    import sys; print(sys.executable)')
        print('and point this script at whatever that prints:')
        print('    python robotic_testing/setup_windows_env.py --env <that path>')
        return 0

    # Search for what the broken modules need before writing anything, so the file is
    # written once, with every directory it turned out to need.
    print('\nLooking for the DLLs the broken modules need, under\n  {}'.format(
        target.base_prefix))
    extra, unfound = discover(target, dll_broken)
    conventional = windows_dlls.candidate_directories(target.base_prefix)
    news = [directory for directory in extra if directory not in conventional]
    for directory in extra:
        print('  found in  {}{}'.format(
            directory, '' if directory in conventional else '   <-- not a conventional place'))
    if not extra:
        print('  nothing found')
    for module in unfound:
        print('  {}: no matching DLL anywhere under the base prefix'.format(module))

    print()
    path = install(target, extra=news)
    print('Installed:\n  {}'.format(path))
    if news:
        print('  including {} director{} found by searching'.format(
            len(news), 'y' if len(news) == 1 else 'ies'))

    print('\nRe-checking in a fresh interpreter')
    still = []
    for module in STDLIB_PROBES + tuple(module for module, _ in JUPYTER_PROBES):
        state, detail = target.verdict(module)
        if state == 'broken':
            if is_dll_failure(detail):
                still.append(module)
                print('  {:<45} FAILED  {}'.format(module, detail))
            else:
                print('  {:<45} package problem (see above)'.format(module))
        else:
            print('  {:<45} {}'.format(module, state))

    if still:
        # sitecustomize was not enough. Fall back to the one directory Windows cannot
        # be talked out of searching: the one holding python.exe.
        print('\nStill failing, so copying those DLLs beside the interpreter --')
        print('the one directory Windows always searches, transitive dependencies')
        print('included, which add_dll_directory does not cover.')
        copied = copy_beside_interpreter(target, still)
        if copied:
            print('  copied {} file(s) into {}'.format(
                len(copied), os.path.dirname(target.python)))
            for _, destination in copied[:12]:
                print('    {}'.format(os.path.basename(destination)))
            if len(copied) > 12:
                print('    ... and {} more'.format(len(copied) - 12))
            print('  (undo by deleting those files; nothing else was changed)')
        else:
            print('  nothing to copy -- every candidate was already there')

        print('\nRe-checking once more')
        remaining = []
        for module in still:
            state, detail = target.verdict(module)
            if state == 'broken':
                remaining.append(module)
                print('  {:<45} FAILED  {}'.format(module, detail))
            else:
                print('  {:<45} {}'.format(module, state))
        still = remaining

    if not still:
        print('\nFixed. Now restart anything already running in this environment.')
        print('PyCharm caches the dead server, so the notebook keeps failing until you do:')
        print('  1. open the Jupyter tool window at the bottom')
        print('  2. press the square stop button')
        print('  3. re-run a cell')
        return 0

    if still:
        print('\nStill broken: {}'.format(', '.join(still)))
        print('\nLoading each candidate DLL by hand, to find the one that is missing')
        print('("DLL load failed" never names it):')
        print(diagnose_dlls(target, still))
        if unfound:
            # The honest diagnosis: this is not a search-path problem at all.
            print()
            print('The DLLs for {} are not present anywhere under'.format(
                ', '.join(unfound)))
            print('{}, so no search path can fix it -- the file is'.format(
                target.base_prefix))
            print('missing from the conda installation, not misplaced within it.')
            print()
            print('Repair conda\'s copy (fastest, keeps this venv and everything in it):')
            for module in unfound:
                package = {'sqlite3': 'sqlite', '_sqlite3': 'sqlite',
                           'ssl': 'openssl', '_ssl': 'openssl',
                           'hashlib': 'openssl', '_hashlib': 'openssl',
                           'lzma': 'xz', '_lzma': 'xz',
                           'bz2': 'bzip2', '_bz2': 'bzip2',
                           'ctypes': 'libffi', '_ctypes': 'libffi'}.get(module)
                if package:
                    print('    conda install -n base --force-reinstall {}'.format(package))
            print()
            print('Then re-run this script. If conda cannot be repaired, rebuild the venv')
            print('on a python.org interpreter, which ships these DLLs itself:')
        else:
            print('The DLLs those need were not found where this could point at them.')
            print('Rebuilding the venv on a python.org interpreter avoids this entirely:')
        print('    py -3.11 -m venv .venv')
        print('    .\\.venv\\Scripts\\Activate.ps1')
        print('    python -m pip install -r robotic_testing\\requirements-vla.txt')
        print('    python -m pip install jupyter ipykernel')
        return 1

    print('\nDone. This environment is fixed for good -- no need to run this again.')
    return 0


if __name__ == '__main__':
    try:
        sys.exit(main())
    except Failure as failure:
        sys.stderr.write('\n{}\n\n'.format(failure))
        sys.exit(1)
    except KeyboardInterrupt:
        sys.exit(130)
