#!/usr/bin/env python3
"""
Repair a conda-based virtualenv on Windows, once, so everything in it works.

    python robotic_testing/setup_windows_env.py             fix this repo's .venv
    python robotic_testing/setup_windows_env.py --check     report, change nothing
    python robotic_testing/setup_windows_env.py --env PATH  fix some other environment
    python robotic_testing/setup_windows_env.py --here      fix the interpreter running this

WHY THIS EXISTS

A venv built from a conda interpreter cannot import parts of its own standard
library. `robotic_testing/common/windows_dlls.py` explains the mechanism in
full; the short version is that conda keeps the DLLs its stdlib C extensions
need in `Library\\bin`, a venv does not inherit that directory, and Python 3.8+
will not find DLLs through PATH. The symptoms:

    ImportError: DLL load failed while importing _ssl      -- no https, so no pip,
                                                              and no google-genai
    ImportError: DLL load failed while importing _sqlite3   -- the Jupyter server
                                                              exits with code 1

vla.py and listen.py import windows_dlls themselves, so they fix their own
process and work with no setup at all. The Jupyter server cannot do that: it
dies inside `import notebook`, long before any repo module is reached. Which is
exactly the maddening case where the scripts run and the notebook does not.

So the same fix has to live where Python runs it during interpreter startup,
and that place is a `sitecustomize.py` on sys.path -- imported by `site` at the
end of initialization, before __main__, before any third-party package.

WHICH ENVIRONMENT IT FIXES

This is the part that bites. `sitecustomize.py` belongs to one environment, and
the broken one is not necessarily the one running this script: on the lab
machine a bare `python` resolves to miniconda even with .venv activated, and
miniconda's own interpreter is fine. Pointed at that, an earlier version of
this script truthfully reported "nothing to fix" and left .venv broken.

So the target is this repo's .venv by default, not whatever is running. --env
names another one; --here means the running interpreter on purpose. Everything
below -- the probes, site-packages, the DLL directories -- is asked of the
*target* interpreter in a subprocess, never inferred from this one.

WHAT IT TOUCHES

One file, inside the target environment:

    <env>\\Lib\\site-packages\\sitecustomize.py

Nothing in the repository, nothing global, nothing outside that environment. A
`sitecustomize.py` this script did not write is never overwritten -- it is
backed up first and the path is printed.
"""
import argparse
import os
import subprocess
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if REPO_ROOT not in sys.path:
    sys.path.insert(0, REPO_ROOT)

from robotic_testing.common import windows_dlls  # noqa: E402

MARKER = '# generated by robotic_testing/setup_windows_env.py'

SITECUSTOMIZE = '''\
{marker}
"""
Let this environment import its own standard library.

This venv's base interpreter keeps the DLLs its stdlib C extensions need (_ssl,
_sqlite3, _hashlib, _lzma, _bz2, _ctypes) in directories a venv does not
inherit, and since Python 3.8 DLL resolution for extension modules ignores PATH.
Without this file those imports fail with "DLL load failed", which takes out
https (pip, google-genai) and the Jupyter server's session store.

`site` imports this module during interpreter startup, before __main__ and
before any third-party package, which is the only point early enough to help a
process like the Jupyter server that fails inside its own imports.

Regenerate with:  python robotic_testing/setup_windows_env.py
Explanation in:   robotic_testing/common/windows_dlls.py
"""
import os
import sys


def _add_base_dll_directories():
    if os.name != 'nt' or not hasattr(os, 'add_dll_directory'):
        return
    root = getattr(sys, 'base_prefix', sys.prefix)
    for parts in {subdirs!r}:
        path = os.path.join(root, *parts)
        if os.path.isdir(path):
            try:
                os.add_dll_directory(path)
            except OSError:
                pass


# Anything raised here would break every interpreter start in this environment,
# including the one needed to undo it, so nothing is allowed to escape.
try:
    _add_base_dll_directories()
except Exception:
    pass
'''

# The stdlib extensions that conda keeps DLLs for. _sqlite3 is the one that stops
# Jupyter; _ssl is the one that stops pip and the planner.
STDLIB_PROBES = ('ssl', 'sqlite3', 'hashlib', 'lzma', 'bz2', 'ctypes')

# The notebook server's own import chain, which is what actually fails in PyCharm.
# Reported only when the package is installed at all: not every environment has
# Jupyter, and a missing notebook is not a DLL problem.
JUPYTER_PROBES = (
    ('notebook.services.sessions.sessionmanager', 'the notebook session store (sqlite3)'),
    ('notebook.notebookapp', 'the notebook server entry point'),
    ('ipykernel', 'the kernel PyCharm starts'),
    ('zmq', 'kernel messaging'),
)


class Failure(Exception):
    """Something the operator needs to fix, reported without a traceback."""


class Environment:
    """One Python environment, asked about itself in a subprocess."""

    def __init__(self, python):
        self.python = os.path.abspath(python)
        if not os.path.isfile(self.python):
            raise Failure('No interpreter at {}'.format(self.python))

    # --- asking the target, never guessing from this process ---------------

    def query(self, expression):
        """Evaluate `expression` in the target and return its printed value."""
        result = subprocess.run(
            [self.python, '-c', 'print({})'.format(expression)],
            stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        if result.returncode != 0:
            raise Failure('{} could not answer `{}`:\n{}'.format(
                self.python, expression,
                result.stderr.decode('utf-8', 'replace').strip()))
        return result.stdout.decode('utf-8', 'replace').strip()

    def probe(self, module):
        """Import `module` in a fresh target interpreter; return the error or None."""
        result = subprocess.run(
            [self.python, '-c', 'import ' + module],
            stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        if result.returncode == 0:
            return None
        lines = [line for line in result.stderr.decode('utf-8', 'replace').splitlines()
                 if line.strip()]
        return lines[-1] if lines else 'exited {}'.format(result.returncode)

    @property
    def version(self):
        return self.query('__import__("sys").version.split()[0]')

    @property
    def base_prefix(self):
        return self.query('getattr(__import__("sys"), "base_prefix", '
                          '__import__("sys").prefix)')

    @property
    def prefix(self):
        return self.query('__import__("sys").prefix')

    @property
    def purelib(self):
        return self.query('__import__("sysconfig").get_paths()["purelib"]')

    @property
    def is_windows(self):
        return self.query('__import__("os").name') == 'nt'

    def dll_directories(self):
        """The DLL directories that exist under the target's base prefix."""
        return windows_dlls.candidate_directories(self.base_prefix)

    @property
    def sitecustomize(self):
        return os.path.join(self.purelib, 'sitecustomize.py')

    def sitecustomize_state(self):
        """'ours', 'foreign', or 'absent'."""
        path = self.sitecustomize
        if not os.path.exists(path):
            return 'absent'
        with open(path, 'r', encoding='utf-8', errors='replace') as handle:
            return 'ours' if MARKER in handle.read() else 'foreign'


# ----------------------------------------------------------------------
# finding the environment to fix
# ----------------------------------------------------------------------

def interpreter_in(root):
    """The interpreter inside an environment directory, Windows or posix layout."""
    for parts in (('Scripts', 'python.exe'), ('bin', 'python'), ('bin', 'python3')):
        candidate = os.path.join(root, *parts)
        if os.path.isfile(candidate):
            return candidate
    return None


def repo_venv():
    """This repo's own .venv interpreter, or None."""
    for name in ('.venv', 'venv'):
        found = interpreter_in(os.path.join(REPO_ROOT, name))
        if found:
            return found
    return None


def resolve_target(env, here):
    """Decide which interpreter to work on, and say why."""
    if env and here:
        raise Failure('--env and --here ask for different environments; pick one.')

    if here:
        return Environment(sys.executable), 'the interpreter running this script (--here)'

    if env:
        # Accept either the interpreter itself or the environment directory.
        if os.path.isdir(env):
            found = interpreter_in(env)
            if not found:
                raise Failure(
                    'No interpreter under {}.\n'
                    'Expected {}\\Scripts\\python.exe (Windows) or {}/bin/python.'
                    .format(env, env.rstrip('\\/'), env.rstrip('\\/')))
            return Environment(found), 'the environment named by --env'
        return Environment(env), 'the interpreter named by --env'

    found = repo_venv()
    if found:
        return Environment(found), "this repo's .venv"

    raise Failure(
        'This repo has no .venv, so there is no default environment to fix.\n'
        'Name one:\n'
        '    python robotic_testing/setup_windows_env.py --env C:\\path\\to\\.venv\n'
        'Or fix the interpreter running this script:\n'
        '    python robotic_testing/setup_windows_env.py --here')


# ----------------------------------------------------------------------

def report(target, why):
    """Print what a fresh interpreter in the target environment can and cannot do."""
    print('Target environment -- {}'.format(why))
    print('  python        {}'.format(target.python))
    print('  version       {}'.format(target.version))
    print('  prefix        {}'.format(target.prefix))
    base = target.base_prefix
    print('  base prefix   {}'.format(base))
    if base == target.prefix:
        print('                (not a venv; its stdlib is its own)')

    if target.python != os.path.abspath(sys.executable):
        # Worth saying plainly: this difference is the whole reason the flag exists.
        print('  note          this is NOT the interpreter running this script')
        print('                ({})'.format(sys.executable))

    directories = target.dll_directories()
    if directories:
        print('  DLL dirs      {}'.format('\n                '.join(directories)))
    else:
        print('  DLL dirs      none under the base prefix (self-contained interpreter)')

    state = {'ours': 'installed by this script',
             'foreign': 'present, written by something else',
             'absent': 'not installed'}[target.sitecustomize_state()]
    print('  sitecustomize {}'.format(state))
    print('                {}'.format(target.sitecustomize))

    print('\nStandard library, in a fresh interpreter')
    broken = []
    for module in STDLIB_PROBES:
        failure = target.probe(module)
        if failure:
            broken.append(module)
            print('  {:<9} FAILED  {}'.format(module, failure))
        else:
            print('  {:<9} ok'.format(module))

    # The notebook chain is reported separately because a missing Jupyter is a
    # different problem from a broken one, and only the second is ours to fix.
    installed = target.probe('notebook') is None or target.probe('ipykernel') is None
    if installed:
        print('\nThe Jupyter import chain, which is what PyCharm runs')
        for module, description in JUPYTER_PROBES:
            failure = target.probe(module)
            if failure is None:
                print('  ok      {}  -- {}'.format(module, description))
            elif 'No module named' in failure:
                print('  absent  {}  -- {} (not installed)'.format(module, description))
            else:
                broken.append(module)
                print('  FAILED  {}  -- {}'.format(module, description))
                print('          {}'.format(failure))
    else:
        print('\nJupyter is not installed in this environment, so the notebook cannot')
        print('run here regardless of DLLs:  "{}" -m pip install jupyter ipykernel'
              .format(target.python))

    return broken


def install(target):
    """Write sitecustomize.py into the target environment. Returns its path."""
    path = target.sitecustomize

    if target.sitecustomize_state() == 'foreign':
        # Somebody else's file. Keep it: it may be doing something this script
        # knows nothing about, and silently replacing it would be a bad trade.
        backup = path + '.bak'
        suffix = 0
        while os.path.exists(backup):
            suffix += 1
            backup = '{}.bak{}'.format(path, suffix)
        os.rename(path, backup)
        print('Moved an existing sitecustomize.py aside:')
        print('  {}'.format(backup))
        print('  If it mattered, merge it into the new one by hand.')

    with open(path, 'w', encoding='utf-8') as handle:
        handle.write(SITECUSTOMIZE.format(
            marker=MARKER, subdirs=windows_dlls._CONDA_DLL_SUBDIRS))
    return path


def main(argv=None):
    parser = argparse.ArgumentParser(
        description='Repair a conda-based virtualenv on Windows so it -- and the Jupyter '
                    'server inside it -- can import ssl, sqlite3 and the rest of its own '
                    'standard library.',
        epilog='With no options it fixes this repository\'s .venv, which is the one '
               'PyCharm runs notebooks in. That is deliberately not "whichever '
               'interpreter runs this script": a bare `python` often resolves '
               'elsewhere.')
    parser.add_argument('--check', action='store_true',
                        help='report what works and what does not, and change nothing')
    parser.add_argument('--env', metavar='PATH',
                        help='the environment to fix: a directory, or a python executable')
    parser.add_argument('--here', action='store_true',
                        help='fix the interpreter running this script, whatever it is')
    args = parser.parse_args(argv)

    target, why = resolve_target(args.env, args.here)

    if not target.is_windows:
        print('{} is not on Windows, so there is nothing to fix.'.format(target.python))
        print('This script exists for venvs built from a conda interpreter on Windows;')
        print('every other platform finds its stdlib DLLs without help.')
        return 0

    broken = report(target, why)

    if args.check:
        print()
        if broken:
            print('Broken: {}'.format(', '.join(broken)))
            print('Fix it with:  python robotic_testing/setup_windows_env.py')
            return 1
        print('Nothing to fix.')
        return 0

    if not broken:
        print('\nNothing to fix: this environment already imports everything it needs.')
        print('If PyCharm still fails, it is running a different interpreter than this')
        print('one. Check it with a notebook cell:')
        print('    import sys; print(sys.executable)')
        print('and point this script at whatever that prints:')
        print('    python robotic_testing/setup_windows_env.py --env <that path>')
        return 0

    print()
    path = install(target)
    print('Installed:\n  {}'.format(path))

    print('\nRe-checking in a fresh interpreter')
    still = []
    for module in STDLIB_PROBES + tuple(module for module, _ in JUPYTER_PROBES):
        failure = target.probe(module)
        if failure is None:
            print('  {:<45} ok'.format(module))
        elif 'No module named' in failure:
            print('  {:<45} absent (not installed)'.format(module))
        else:
            still.append(module)
            print('  {:<45} FAILED  {}'.format(module, failure))

    if still:
        print('\nStill broken: {}'.format(', '.join(still)))
        print('The DLLs those need are not under {}.'.format(target.base_prefix))
        print('Rebuilding the venv on a python.org interpreter avoids this entirely:')
        print('    py -3.11 -m venv .venv')
        print('    .\\.venv\\Scripts\\Activate.ps1')
        print('    python -m pip install -r robotic_testing\\requirements-vla.txt')
        print('    python -m pip install jupyter ipykernel')
        return 1

    print('\nDone. This environment is fixed for good -- no need to run this again.')
    print('Now restart anything already running in it. PyCharm caches the dead')
    print('server, so the notebook keeps failing until you do:')
    print('  1. open the Jupyter tool window at the bottom')
    print('  2. press the square stop button')
    print('  3. re-run a cell')
    return 0


if __name__ == '__main__':
    try:
        sys.exit(main())
    except Failure as failure:
        sys.stderr.write('\n{}\n\n'.format(failure))
        sys.exit(1)
    except KeyboardInterrupt:
        sys.exit(130)
